// CommonPropertyIDs.h

#ifndef COMMON_PROPERTY_IDS_H
#define COMMON_PROPERTY_IDS_H

#include <SupportDefs.h>

enum {
	PROPERTY_OPACITY	= 0,
	PROPERTY_MIN_OPACITY,

	PROPERTY_BLENDING_MODE,
	PROPERTY_COLOR,
	PROPERTY_GRADIENT,

	PROPERTY_RADIUS,
	PROPERTY_MIN_RADIUS,

	PROPERTY_HARDNESS,
	PROPERTY_MIN_HARDNESS,

	PROPERTY_NO_ANTIALIASING,
	PROPERTY_SPACING,

	PROPERTY_PRESSURE_CONTROLS_OPACITY,
	PROPERTY_PRESSURE_CONTROLS_RADIUS,
	PROPERTY_PRESSURE_CONTROLS_HARDNESS,
	PROPERTY_PRESSURE_CONTROLS_SPACING,
	PROPERTY_TILT,

	PROPERTY_BLUR_RADIUS,

	PROPERTY_TEXT,
	PROPERTY_FONT,
	PROPERTY_FONT_SIZE,
	PROPERTY_FONT_X_SCALE,
	PROPERTY_FONT_LINE_SCALE,
	PROPERTY_FONT_HINTING,
	PROPERTY_FONT_KERNING,
	PROPERTY_ALIGNMENT,
	PROPERTY_WIDTH,
	PROPERTY_PARAGRAPH_INSET,
	PROPERTY_PARAGRAPH_SPACING,

	PROPERTY_PATH,
	PROPERTY_OUTLINE,
	PROPERTY_OUTLINE_WIDTH,
	PROPERTY_CLOSED,
	PROPERTY_CAP_MODE,
	PROPERTY_JOIN_MODE,
	PROPERTY_FILLING_RULE,

	PROPERTY_X_OFFSET,
	PROPERTY_Y_OFFSET,

	PROPERTY_BRIGHTNESS,
	PROPERTY_CONTRAST,
	PROPERTY_SATURATION,

	PROPERTY_ANGLE,
	PROPERTY_BLUR_ALPHA,

	PROPERTY_HALFTONE_MODE,

	PROPERTY_STRENGTH,
	PROPERTY_LUMINANCE_ONLY,

	PROPERTY_WARPSHARP_LAMBDA,
	PROPERTY_WARPSHARP_MU,
	PROPERTY_WARPSHARP_NON_MAX_SUPR,

	PROPERTY_BITMAP_INTERPOLATION,

	// properties used by CImg library based De-Noise filter
	PROPERTY_CIMG_AMPLITUDE,
	PROPERTY_CIMG_SHARPNESS,
	PROPERTY_CIMG_ANISOTROPY,
	PROPERTY_CIMG_ALPHA,
	PROPERTY_CIMG_SIGMA,
	PROPERTY_CIMG_DL,
	PROPERTY_CIMG_DA,
	PROPERTY_CIMG_GAUSS_PRECISION,
	PROPERTY_CIMG_INTERPOLATION,
	PROPERTY_CIMG_FAST_APPROXIMATION,
};

const char*		name_for_id(int32 id);

#endif // PROPERTY_H


